name: BUG 提交
description: 提交产品缺陷帮助我们更好的改进
title: "[BUG]"
labels: "类型: 缺陷"
body:
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: versionApp
    validations:
      required: true
    attributes:
      label: "App 版本"
      description: "设置页面，最下面查看当前软件版本。"
  - type: input
    id: versionCore
    validations:
      required: false
    attributes:
      label: "内核版本"
      description: "设置页面，最上面查看当前内核版本。"
  - type: input
    id: versionWindows
    validations:
      required: false
    attributes:
      label: "Windows版本和版本号"
      description: "设置页面，系统信息，例如：Windows 11 专业版 23H2"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    attributes:
      label: "问题描述"
      description: "简要描述您碰到的问题"
    validations:
      required: true
  - type: textarea
    id: how-happened
    attributes:
      label: "重现步骤"
      description: "如果操作可以重现该问题"
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: "期待的正确结果"
  - type: textarea
    id: logs
    attributes:
      label: "相关日志输出"
      description: "请复制并粘贴任何相关的日志输出。 这将自动格式化为代码，因此无需反引号。"
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"