name: 需求建议
description: 提出针对本项目的想法和建议
title: "[FEATURE]"
labels: enhancement
body:
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "App 版本"
      description: "设置页面，最下面查看当前软件版本。"
  - type: input
    id: versionCore
    validations:
      required: false
    attributes:
      label: "内核版本"
      description: "设置页面，最上面查看当前内核版本。"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: description
    attributes:
      label: "请描述您的需求或者改进建议"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "请描述你建议的实现方案"
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"