name: Release Windows

on:
  workflow_dispatch:

jobs:
  build:
    if: contains('["xlc520"]', github.actor)
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        run: npm install -g pnpm@9

      - name: Install dependencies
        run: pnpm install

      - name: Compile project
        run: pnpm run build:compile

      - name: Build for Windows
        run: pnpm run build:win

      # 上传便携版zip包
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: easytier-manager-pro-portable
          path: easytier-manager-pro.zip

      # 上传 NSIS 安装包
      - name: Upload NSIS artifact
        uses: actions/upload-artifact@v4
        with:
          name: easytier-manager-pro-setup
          path: src-tauri/target/release/bundle/nsis/*.exe

      # 上传 MSI 安装包
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: easytier-manager-pro-msi
          path: src-tauri/target/release/bundle/msi/*.msi

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: false
          files: |
            release/*.exe
            release/*.zip
            release/*.blockmap
            release/latest*.yml
